# Generated by Django 3.1 on 2020-09-10 23:54

from django.db import migrations, models
import users.managers.user_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=70, verbose_name='First name')),
                ('last_name', models.CharField(max_length=70, verbose_name='Last name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars', verbose_name='Avatar')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last visited')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Access to admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', users.managers.user_manager.UserManager()),
            ],
        ),
    ]
