# Generated by Django 3.1 on 2020-09-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_bitbacket',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bitbacket account'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook account'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_github',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Github account'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_gitlab',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gitlab account'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_google',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google account'),
        ),
    ]
